/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as ClientLayoutRouteImport } from './routes/client/_layout'

const AdminLayoutIndexLazyRouteImport = createFileRoute('/admin/_layout/')()
const ClientLayoutIndexLazyRouteImport = createFileRoute('/client/_layout/')()
const AdminLayoutDomainsIndexLazyRouteImport = createFileRoute(
  '/admin/_layout/domains/',
)()
const AdminLayoutHostingIndexLazyRouteImport = createFileRoute(
  '/admin/_layout/hosting/',
)()
const AdminLayoutHostingIdLazyRouteImport = createFileRoute(
  '/admin/_layout/hosting/$id',
)()
const ClientLayoutCartIndexLazyRouteImport = createFileRoute(
  '/client/_layout/cart/',
)()
const ClientLayoutHostingIndexLazyRouteImport = createFileRoute(
  '/client/_layout/hosting/',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLayoutRoute = ClientLayoutRouteImport.update({
  id: '/client/_layout',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexLazyRoute = AdminLayoutIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin/_layout/index.lazy').then((d) => d.Route),
)
const ClientLayoutIndexLazyRoute = ClientLayoutIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientLayoutRoute,
} as any).lazy(() =>
  import('./routes/client/_layout/index.lazy').then((d) => d.Route),
)
const AdminLayoutDomainsIndexLazyRoute =
  AdminLayoutDomainsIndexLazyRouteImport.update({
    id: '/domains/',
    path: '/domains/',
    getParentRoute: () => AdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/admin/_layout/domains/index.lazy').then((d) => d.Route),
  )
const AdminLayoutHostingIndexLazyRoute =
  AdminLayoutHostingIndexLazyRouteImport.update({
    id: '/hosting/',
    path: '/hosting/',
    getParentRoute: () => AdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/admin/_layout/hosting/index.lazy').then((d) => d.Route),
  )
const AdminLayoutHostingIdLazyRoute =
  AdminLayoutHostingIdLazyRouteImport.update({
    id: '/hosting/$id',
    path: '/hosting/$id',
    getParentRoute: () => AdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/admin/_layout/hosting/$id.lazy').then((d) => d.Route),
  )
const ClientLayoutCartIndexLazyRoute =
  ClientLayoutCartIndexLazyRouteImport.update({
    id: '/cart/',
    path: '/cart/',
    getParentRoute: () => ClientLayoutRoute,
  } as any).lazy(() =>
    import('./routes/client/_layout/cart/index.lazy').then((d) => d.Route),
  )
const ClientLayoutHostingIndexLazyRoute =
  ClientLayoutHostingIndexLazyRouteImport.update({
    id: '/hosting/',
    path: '/hosting/',
    getParentRoute: () => ClientLayoutRoute,
  } as any).lazy(() =>
    import('./routes/client/_layout/hosting/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/client': typeof ClientLayoutRouteWithChildren
  '/admin/': typeof AdminLayoutIndexLazyRoute
  '/client/': typeof ClientLayoutIndexLazyRoute
  '/admin/hosting/$id': typeof AdminLayoutHostingIdLazyRoute
  '/admin/domains/': typeof AdminLayoutDomainsIndexLazyRoute
  '/admin/hosting/': typeof AdminLayoutHostingIndexLazyRoute
  '/client/cart/': typeof ClientLayoutCartIndexLazyRoute
  '/client/hosting/': typeof ClientLayoutHostingIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutIndexLazyRoute
  '/client': typeof ClientLayoutIndexLazyRoute
  '/admin/hosting/$id': typeof AdminLayoutHostingIdLazyRoute
  '/admin/domains': typeof AdminLayoutDomainsIndexLazyRoute
  '/admin/hosting': typeof AdminLayoutHostingIndexLazyRoute
  '/client/cart': typeof ClientLayoutCartIndexLazyRoute
  '/client/hosting': typeof ClientLayoutHostingIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/client/_layout': typeof ClientLayoutRouteWithChildren
  '/admin/_layout/': typeof AdminLayoutIndexLazyRoute
  '/client/_layout/': typeof ClientLayoutIndexLazyRoute
  '/admin/_layout/hosting/$id': typeof AdminLayoutHostingIdLazyRoute
  '/admin/_layout/domains/': typeof AdminLayoutDomainsIndexLazyRoute
  '/admin/_layout/hosting/': typeof AdminLayoutHostingIndexLazyRoute
  '/client/_layout/cart/': typeof ClientLayoutCartIndexLazyRoute
  '/client/_layout/hosting/': typeof ClientLayoutHostingIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/admin/'
    | '/client/'
    | '/admin/hosting/$id'
    | '/admin/domains/'
    | '/admin/hosting/'
    | '/client/cart/'
    | '/client/hosting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/admin/hosting/$id'
    | '/admin/domains'
    | '/admin/hosting'
    | '/client/cart'
    | '/client/hosting'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/client/_layout'
    | '/admin/_layout/'
    | '/client/_layout/'
    | '/admin/_layout/hosting/$id'
    | '/admin/_layout/domains/'
    | '/admin/_layout/hosting/'
    | '/client/_layout/cart/'
    | '/client/_layout/hosting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  ClientLayoutRoute: typeof ClientLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/_layout': {
      id: '/client/_layout'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexLazyRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/client/_layout/': {
      id: '/client/_layout/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientLayoutIndexLazyRouteImport
      parentRoute: typeof ClientLayoutRoute
    }
    '/admin/_layout/domains/': {
      id: '/admin/_layout/domains/'
      path: '/domains'
      fullPath: '/admin/domains/'
      preLoaderRoute: typeof AdminLayoutDomainsIndexLazyRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/hosting/': {
      id: '/admin/_layout/hosting/'
      path: '/hosting'
      fullPath: '/admin/hosting/'
      preLoaderRoute: typeof AdminLayoutHostingIndexLazyRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/hosting/$id': {
      id: '/admin/_layout/hosting/$id'
      path: '/hosting/$id'
      fullPath: '/admin/hosting/$id'
      preLoaderRoute: typeof AdminLayoutHostingIdLazyRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/client/_layout/cart/': {
      id: '/client/_layout/cart/'
      path: '/cart'
      fullPath: '/client/cart/'
      preLoaderRoute: typeof ClientLayoutCartIndexLazyRouteImport
      parentRoute: typeof ClientLayoutRoute
    }
    '/client/_layout/hosting/': {
      id: '/client/_layout/hosting/'
      path: '/hosting'
      fullPath: '/client/hosting/'
      preLoaderRoute: typeof ClientLayoutHostingIndexLazyRouteImport
      parentRoute: typeof ClientLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexLazyRoute: typeof AdminLayoutIndexLazyRoute
  AdminLayoutHostingIdLazyRoute: typeof AdminLayoutHostingIdLazyRoute
  AdminLayoutDomainsIndexLazyRoute: typeof AdminLayoutDomainsIndexLazyRoute
  AdminLayoutHostingIndexLazyRoute: typeof AdminLayoutHostingIndexLazyRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexLazyRoute: AdminLayoutIndexLazyRoute,
  AdminLayoutHostingIdLazyRoute: AdminLayoutHostingIdLazyRoute,
  AdminLayoutDomainsIndexLazyRoute: AdminLayoutDomainsIndexLazyRoute,
  AdminLayoutHostingIndexLazyRoute: AdminLayoutHostingIndexLazyRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface ClientLayoutRouteChildren {
  ClientLayoutIndexLazyRoute: typeof ClientLayoutIndexLazyRoute
  ClientLayoutCartIndexLazyRoute: typeof ClientLayoutCartIndexLazyRoute
  ClientLayoutHostingIndexLazyRoute: typeof ClientLayoutHostingIndexLazyRoute
}

const ClientLayoutRouteChildren: ClientLayoutRouteChildren = {
  ClientLayoutIndexLazyRoute: ClientLayoutIndexLazyRoute,
  ClientLayoutCartIndexLazyRoute: ClientLayoutCartIndexLazyRoute,
  ClientLayoutHostingIndexLazyRoute: ClientLayoutHostingIndexLazyRoute,
}

const ClientLayoutRouteWithChildren = ClientLayoutRoute._addFileChildren(
  ClientLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  ClientLayoutRoute: ClientLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
